/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pantalla_home;

/**
 *
 * @author lucho
 */
public class Stats extends javax.swing.JFrame {

    /**
     * Creates new form Stats
     */
    Singleton_BD singleton_bd = Singleton_BD.getInstance();
    public Stats() {
        initComponents();
        singleton_bd.calcularTOP1();
        singleton_bd.calcularTOP2();
        singleton_bd.calcularTOP3();
        
        this.label_primero.setText(singleton_bd.getTOP1().getUsuario());
        this.label_segundo.setText(singleton_bd.getTOP2().getUsuario());
        this.label_tercero.setText(singleton_bd.getTOP3().getUsuario());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_ranking = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_segundo = new javax.swing.JLabel();
        label_primero = new javax.swing.JLabel();
        label_tercero = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 800));
        setMinimumSize(new java.awt.Dimension(450, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_ranking.setFont(new java.awt.Font("Bebas", 1, 55)); // NOI18N
        label_ranking.setForeground(new java.awt.Color(255, 255, 255));
        label_ranking.setText("RANKING");
        getContentPane().add(label_ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 190, 80));

        jPanel1.setLayout(new java.awt.BorderLayout());

        label_segundo.setFont(new java.awt.Font("Bebas", 1, 36)); // NOI18N
        label_segundo.setForeground(new java.awt.Color(153, 153, 153));
        label_segundo.setText("sec");
        jPanel1.add(label_segundo, java.awt.BorderLayout.CENTER);

        label_primero.setFont(new java.awt.Font("Bebas", 1, 48)); // NOI18N
        label_primero.setForeground(new java.awt.Color(255, 204, 0));
        label_primero.setText("FIRST");
        jPanel1.add(label_primero, java.awt.BorderLayout.PAGE_START);

        label_tercero.setFont(new java.awt.Font("Bebas", 1, 24)); // NOI18N
        label_tercero.setForeground(new java.awt.Color(153, 102, 0));
        label_tercero.setText("tHIRD");
        jPanel1.add(label_tercero, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 320, 160));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonCruz.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 40, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoRanking.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_primero;
    private javax.swing.JLabel label_ranking;
    private javax.swing.JLabel label_segundo;
    private javax.swing.JLabel label_tercero;
    // End of variables declaration//GEN-END:variables
}
