/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pantalla_home;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author lucho
 */
public class Vista_Config extends javax.swing.JFrame{

    /**
     * Creates new form Vista_Config
     * 
     */
    boolean estaMute = false;
    Music m ;
    public Vista_Config() {
        initComponents();
    }
    
    public void recibirMusica(Music m){
        this.m=m;
    }
    
    /* Metodos test */
    
    public JButton getBotonSwitch(){
        return this.boton_mutear_desmutear;
    }
    
    public JLabel getLabelEnabled(){
        return this.label_enabled;
    }
    
    public JLabel getLabelDisabled(){
        return this.label_disabled;
    }
    
    public JButton getBotonCerrar(){
        return this.boton_cerrar;
    }
    
    public boolean getEstaMute(){
        return this.estaMute;
    }
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_cerrar = new javax.swing.JButton();
        boton_mutear_desmutear = new javax.swing.JButton();
        label_enabled = new javax.swing.JLabel();
        label_disabled = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonCruz.png"))); // NOI18N
        boton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 40, 20));

        boton_mutear_desmutear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sonidoMuted.jpg"))); // NOI18N
        boton_mutear_desmutear.setBorder(new javax.swing.border.MatteBorder(null));
        boton_mutear_desmutear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mutear_desmutearActionPerformed(evt);
            }
        });
        getContentPane().add(boton_mutear_desmutear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        label_enabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sonidoEnabled.jpeg"))); // NOI18N
        getContentPane().add(label_enabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        label_disabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sonidoMuted.png"))); // NOI18N
        getContentPane().add(label_disabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoConfig.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_mutear_desmutearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mutear_desmutearActionPerformed
        // TODO add your handling code here:
        if (estaMute==false){
            label_enabled.setVisible(false);
            label_disabled.setVisible(true);
            estaMute=true;
            this.m.disperformMusic();
          
        }else{
            label_enabled.setVisible(true);
            label_disabled.setVisible(false);
            estaMute=false;
            this.m.performMusic();
        }
    }//GEN-LAST:event_boton_mutear_desmutearActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void boton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_boton_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cerrar;
    private javax.swing.JButton boton_mutear_desmutear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_disabled;
    private javax.swing.JLabel label_enabled;
    // End of variables declaration//GEN-END:variables
}
