/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pantalla_home;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.Clip;
import javax.sound.sampled.AudioSystem;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author lucho
 */
public class Vista_Home extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Home
     */
    public Clip clip;
    public AudioInputStream audioInput;
    boolean sonidoMuted = false;
    boolean reglasVisible =false;
    //int aux = 0;
    //MusicaHome musicaH=new MusicaHome();
    Music m ;
   
//boolean backReglas
    //this.jLabel1.setVisible(false);
    public Vista_Home(Music m) {
        this.m = m;
        initComponents();
        this.setLocationRelativeTo(null);
        //Music_Nav musicNav = new Music_Nav();
        m.performMusic();
        //inicioDeSonido("musicHome.wav");
        
        
        
        this.label_reglas.setVisible(false);
        this.boton_cerrar_reglas.setVisible(false);
    }
    
    public Vista_Home(){
        initComponents();
        this.setLocationRelativeTo(null);
        this.label_reglas.setVisible(false);
        this.boton_cerrar_reglas.setVisible(false);
    }
    public void inicioDeSonido(String dir){
            try{
            File musicPath = new File(dir);
            if(musicPath.exists()){
                this.audioInput = AudioSystem.getAudioInputStream(musicPath);
                this.clip= AudioSystem.getClip();
                this.clip.open(audioInput);
               // if(sonidoMuted==false){
                this.clip.start();
            }else{
                System.out.println("no pude abrir");
            }
            
        }catch(Exception e){
            System.out.println("no pude abreeeeir");
            
        }
    }
    public void sonidoFondoInicial(String dir,boolean a){
        //if 
        if(a == false){
            this.clip.stop();
        }else{
            this.clip.start();
        }
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_jugar = new javax.swing.JButton();
        boton_muted = new javax.swing.JButton();
        boton_reglas = new javax.swing.JButton();
        boton_stats = new javax.swing.JButton();
        boton_exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        boton_cerrar_reglas = new javax.swing.JButton();
        label_reglas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonJugar.jpg"))); // NOI18N
        boton_jugar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_jugarMouseClicked(evt);
            }
        });
        boton_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_jugarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 120, 50));

        boton_muted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sonidoMuted.jpg"))); // NOI18N
        boton_muted.setBorder(new javax.swing.border.MatteBorder(null));
        boton_muted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_mutedMouseClicked(evt);
            }
        });
        boton_muted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mutedActionPerformed(evt);
            }
        });
        jPanel1.add(boton_muted, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        boton_reglas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonReglas.png"))); // NOI18N
        boton_reglas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_reglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_reglasMouseClicked(evt);
            }
        });
        boton_reglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_reglasActionPerformed(evt);
            }
        });
        jPanel1.add(boton_reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 382, 120, 50));

        boton_stats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonStats.png"))); // NOI18N
        boton_stats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_statsActionPerformed(evt);
            }
        });
        jPanel1.add(boton_stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 120, 50));

        boton_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonSalir.png"))); // NOI18N
        boton_exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_exitActionPerformed(evt);
            }
        });
        jPanel1.add(boton_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 502, 120, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucho\\Documents\\DAMASCHINASDESIGN\\rayo.gif")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 50, 110));

        boton_cerrar_reglas.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucho\\Documents\\DAMASCHINASDESIGN\\botonBack.png")); // NOI18N
        boton_cerrar_reglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cerrar_reglasActionPerformed(evt);
            }
        });
        jPanel1.add(boton_cerrar_reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 20, 20));

        label_reglas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reglas.png"))); // NOI18N
        label_reglas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                label_reglasKeyPressed(evt);
            }
        });
        jPanel1.add(label_reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 660, 590));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, 30));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        label_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo1.jpg"))); // NOI18N
        jPanel1.add(label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_mutedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mutedActionPerformed
        // TODO add your handling code here:
        /* comentado pa ver si funca con Strategy
        String filepath = "musicHome.wav";
        
        ImageIcon  icon;
        //icon.
        //new javax.swing.ImageIcon(getClass().getResource("/botonJugar.jpg"));
        icon = new ImageIcon(getClass().getResource("/rojo.jpg"));
        ImageIcon vuelta;
        vuelta = new ImageIcon(getClass().getResource("/sonidoMuted.jpg"));
        
        if(sonidoMuted==false){
            boton_muted.setIcon(icon);
            sonidoFondoInicial(filepath,sonidoMuted);
            sonidoMuted = true;
            
        }else{
            boton_muted.setIcon(vuelta);
            sonidoFondoInicial(filepath,sonidoMuted);
            sonidoMuted = false;
            
        }*/
        ImageIcon icon;
        icon = new ImageIcon(getClass().getResource("/rojo.jpg"));
        ImageIcon vuelta;
        vuelta = new ImageIcon(getClass().getResource("/sonidoMuted.jpg"));
        if(this.sonidoMuted ==false){
            this.m.disperformMusic();
            sonidoMuted=true;
            boton_muted.setIcon(icon);
        }else{
            this.m.reanuderMusic();
            sonidoMuted=false;
            boton_muted.setIcon(vuelta);
        }
    }//GEN-LAST:event_boton_mutedActionPerformed

    private void boton_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_jugarActionPerformed
        // TODO add your handling code here:
        //Vista_Tablero tablero = new Vista_Tablero();
        Vista_SeleccionModo seleccion = new Vista_SeleccionModo();
        seleccion.setLocationRelativeTo(null);
        seleccion.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_boton_jugarActionPerformed

    private void boton_jugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_jugarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boton_jugarMouseClicked

    private void boton_mutedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_mutedMouseClicked
        // TODO add your handling code here:
        

        //jButton3.setIconImage(icon.getImage());
        //this.setIcon(new javax.swing.ImageIcon());
        
        
        
        
    }//GEN-LAST:event_boton_mutedMouseClicked

    private void boton_reglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_reglasActionPerformed
        // TODO add your handling code here:
        //this.jLabel4.setVisible(false);
        this.label_reglas.setVisible(reglasVisible);
        this.boton_cerrar_reglas.setVisible(true);
    }//GEN-LAST:event_boton_reglasActionPerformed

    private void boton_statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_statsActionPerformed
        // TODO add your handling code here:
      //  this.jLabel5.setText("nice");
    }//GEN-LAST:event_boton_statsActionPerformed

    private void boton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_boton_exitActionPerformed

    private void boton_reglasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_reglasMouseClicked
        // TODO add your handling code here:
        this.label_reglas.setVisible(true);
    }//GEN-LAST:event_boton_reglasMouseClicked

    private void boton_cerrar_reglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cerrar_reglasActionPerformed
        // TODO add your handling code here:
        this.label_reglas.setVisible(false);
        this.boton_cerrar_reglas.setVisible(false);
    }//GEN-LAST:event_boton_cerrar_reglasActionPerformed

    private void label_reglasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_label_reglasKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_label_reglasKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:\
       // this.musicaH.sonar(0);
       this.m.disperformMusic();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //this.musicaH.sonar(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cerrar_reglas;
    private javax.swing.JButton boton_exit;
    private javax.swing.JButton boton_jugar;
    private javax.swing.JButton boton_muted;
    private javax.swing.JButton boton_reglas;
    private javax.swing.JButton boton_stats;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_fondo;
    private javax.swing.JLabel label_reglas;
    // End of variables declaration//GEN-END:variables
}
