/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pantalla_home;
import java.awt.event.ActionEvent;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.Clip;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author lucho
 */
public class Vista_Home extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Home
     */
    public Clip clip;
    public AudioInputStream audioInput;
    boolean reglasVisible =false;
    //int aux = 0;
    //MusicaHome musicaH=new MusicaHome();
    Music m ;
    Vista_Config config = new Vista_Config();
    
    
    /* Variables usadas en TESTS*/
    
    boolean exit_pulse = false;
    boolean stats_pulse = false;
    boolean config_pulse = false;
    
    
    public Vista_Home(Music m, Vista_Config c) {
        this.m = m;
        initComponents();
        this.setLocationRelativeTo(null);
        //Music_Nav musicNav = new Music_Nav();
       // m.performMusic();
        //inicioDeSonido("musicHome.wav");
        config =c;
        
        
        this.label_reglas.setVisible(false);
        this.boton_cerrar_reglas.setVisible(false);
    }
    
    public Vista_Home(){
        initComponents();
        this.setLocationRelativeTo(null);
        this.label_reglas.setVisible(false);
        this.boton_cerrar_reglas.setVisible(false);
    }
    
    /* Metodos usados en TEST*/
    public boolean getReglasVisible(){
        return this.label_reglas.isVisible();
    }
    
    public boolean getBCReglasVisible(){
        return this.boton_cerrar_reglas.isVisible();
    }
    
    public JButton getBotonExit(){
        return this.boton_exit;
    }
    public boolean  getAux(){
        return this.exit_pulse;
    }
    
    public JButton getBotonJugar(){
        return this.boton_jugar;
    }
    
    public JButton getBotonReglas(){
        return this.boton_reglas;
    }
    
    public JButton getBotonCerrarReglas(){
        return this.boton_cerrar_reglas;
    }
    
    public JLabel getLayoutReglas(){
        return this.label_reglas;
    }
    
    public JButton getBotonStats(){
        return this.boton_stats;
    }
    
    public boolean getMuestraStats(){
        return this.stats_pulse;
    }
    
    public JButton getBotonConfig(){
        return this.boton_config;
    }
    
    public boolean getMuestraConfig(){
        return this.config_pulse;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_jugar = new javax.swing.JButton();
        boton_reglas = new javax.swing.JButton();
        boton_stats = new javax.swing.JButton();
        boton_exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        boton_cerrar_reglas = new javax.swing.JButton();
        boton_config = new javax.swing.JButton();
        label_reglas = new javax.swing.JLabel();
        label_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonJugar.jpg"))); // NOI18N
        boton_jugar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_jugarMouseClicked(evt);
            }
        });
        boton_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_jugarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 120, 50));

        boton_reglas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonReglas.png"))); // NOI18N
        boton_reglas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_reglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_reglasMouseClicked(evt);
            }
        });
        boton_reglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_reglasActionPerformed(evt);
            }
        });
        jPanel1.add(boton_reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 382, 120, 50));

        boton_stats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonStats.png"))); // NOI18N
        boton_stats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_statsActionPerformed(evt);
            }
        });
        jPanel1.add(boton_stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 120, 50));

        boton_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonSalir.png"))); // NOI18N
        boton_exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_exitActionPerformed(evt);
            }
        });
        jPanel1.add(boton_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 502, 120, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucho\\Documents\\DAMASCHINASDESIGN\\rayo.gif")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 50, 110));

        boton_cerrar_reglas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonCruz.png"))); // NOI18N
        boton_cerrar_reglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cerrar_reglasActionPerformed(evt);
            }
        });
        jPanel1.add(boton_cerrar_reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 20, 20));

        boton_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonConfig.png"))); // NOI18N
        boton_config.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_configActionPerformed(evt);
            }
        });
        jPanel1.add(boton_config, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 50, 50));

        label_reglas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reglas.png"))); // NOI18N
        label_reglas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                label_reglasKeyPressed(evt);
            }
        });
        jPanel1.add(label_reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 660, 590));

        label_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo1.jpg"))); // NOI18N
        jPanel1.add(label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_jugarActionPerformed
        // TODO add your handling code here:
        //Vista_Tablero tablero = new Vista_Tablero();
        
        Vista_SeleccionModo seleccion = new Vista_SeleccionModo(m,config);
        seleccion.setLocationRelativeTo(null);
        seleccion.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_boton_jugarActionPerformed

    private void boton_jugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_jugarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boton_jugarMouseClicked

    private void boton_reglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_reglasActionPerformed
        // TODO add your handling code here:
        //this.jLabel4.setVisible(false);
        this.label_reglas.setVisible(true);
        this.boton_cerrar_reglas.setVisible(true);
    }//GEN-LAST:event_boton_reglasActionPerformed

    private void boton_statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_statsActionPerformed
        // TODO add your handling code here:
      //  this.jLabel5.setText("nice");
        Vista_Stats st = new Vista_Stats();
        st.setLocationRelativeTo(null);
        st.setVisible(true);
        this.stats_pulse = true; // FLAG TEST
        
        
    }//GEN-LAST:event_boton_statsActionPerformed

    private void boton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_exitActionPerformed
        // TODO add your handling code here:

        this.exit_pulse=true; //FLAG TEST
        System.exit(0);
    }//GEN-LAST:event_boton_exitActionPerformed

    private void boton_reglasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_reglasMouseClicked
        // TODO add your handling code here:
        this.label_reglas.setVisible(true);
    }//GEN-LAST:event_boton_reglasMouseClicked

    private void boton_cerrar_reglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cerrar_reglasActionPerformed
        // TODO add your handling code here:
        this.label_reglas.setVisible(false);
        this.boton_cerrar_reglas.setVisible(false);
    }//GEN-LAST:event_boton_cerrar_reglasActionPerformed

    private void label_reglasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_label_reglasKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_label_reglasKeyPressed

    private void boton_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_configActionPerformed
        // TODO add your handling code here:\
       // this.musicaH.sonar(0);
     
       
       this.config.setVisible(true);
       this.config_pulse = this.config.isVisible();
       this.config.recibirMusica(m);
       /*this.m.disperformMusic();*/
    }//GEN-LAST:event_boton_configActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cerrar_reglas;
    private javax.swing.JButton boton_config;
    private javax.swing.JButton boton_exit;
    private javax.swing.JButton boton_jugar;
    private javax.swing.JButton boton_reglas;
    private javax.swing.JButton boton_stats;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_fondo;
    private javax.swing.JLabel label_reglas;
    // End of variables declaration//GEN-END:variables
}
