name: testssss

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  

  vault:
    name: vault
    runs-on: ubuntu-latest
    env:
      HCP_CLIENT_ID: A
      HCP_CLIENT_SECRET: B
    steps:
      - name: check
        uses: actions/checkout@v2
      - name: Obtener token
        id: obtener-token
        run: |
            HCP_API_TOKEN=$(curl --location 'https://auth.hashicorp.com/oauth/token' \
            --header 'content-type: application/json' \
            --data '{
              "audience": "https://api.hashicorp.cloud",
              "grant_type": "client_credentials",
              "client_id": "'$HCP_CLIENT_ID'",
              "client_secret": "'$HCP_CLIENT_SECRET'"
              }' | jq -r .access_token)
            
      - name:  gettok
        id: sonar-tok
        run: |
            curl \
            --location "https://api.cloud.hashicorp.com/secrets/2023-06-13/organizations/3ef78803-15d7-47fb-b3f1-a1265680841b/projects/2b9322b9-f5cb-4f22-b027-c30b171c103c/apps/damaschinas/open" \
            --request GET \
            --header "Authorization: Bearer $HCP_API_TOKEN" | jq
            echo "Respuesta SONAR_TOKEN: $SONAR_TOKEN"
              