
name: testssss

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mi-trabajo:
    runs-on: ubuntu-latest
    env:
      FLAG: 0 
    steps:
    - name: Inicio
      run: Estoy variando la flag
    - name: El valor es
      run: echo $FLAG
    - name: Con If
      run: |
          if [ "$FLAG" -eq "1" ]; then
          echo "La bandera es 1, realiza acciones basadas en esto."
          # Realiza acciones basadas en la bandera
          else
          echo "La bandera es 0, ejecuta acciones alternativas."
          # Realiza acciones alternativas
          fi
    - name: Cambiar valor
      run: |
          echo "::set-env name=FLAG::1"

    - name: UltValor
      run: echo $FLAG