name: testssss

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mi-trabajo:
    runs-on: ubuntu-latest
    env:
      DR: 0 
    steps:
    - name: Inicio
      run: echo "Estoy variando la flag"
    - name: Test cluster use
      run: |
          if [ "$DR" -eq "1" ]; then
          echo "La bandera es 1, realiza acciones basadas en esto."
          # Realiza acciones basadas en la bandera
          else
          echo "La bandera es 0, ejecuta acciones alternativas."
          # Realiza acciones alternativas
          fi
    - name: Cambiar valor
      run: |
          echo "DR=1" >> $GITHUB_ENV

    - name: Ult Valor VAS
      run: echo "$DR"
