name: testssss

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mi-trabajo:
    runs-on: ubuntu-latest
    steps:
    - name: Inicio
      run: echo "Estoy variando la flag"
    - name: Test cluster use
      run: |
          if [ "$DR" -eq "1" ]; then
          echo "La bandera es 1, realiza acciones basadas en esto."
          # Realiza acciones basadas en la bandera
          else
          echo "La bandera es 0, ejecuta acciones alternativas."
          # Realiza acciones alternativas
          fi
    - name: Guardar valor DR en un archivo de artefacto
      run: echo "$DR" > dr.txt
      post-actions:
        - name: Subir archivo de artefacto
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: dr-artifact
            path: dr.txt

  otro-trabajo:
    needs: mi-trabajo
    runs-on: ubuntu-latest
    steps:
    - name: Descargar archivo de artefacto
      uses: actions/download-artifact@v2
      with:
        name: dr-artifact
    - name: Leer valor DR
      run: |
        DR=$(cat dr-artifact/dr.txt)
        echo "El valor de DR es $DR"