on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 9 10 * * *
name: Semgrep
jobs:



  check-horusec:
    name: horuscc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: CheckSecrets
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Horusec
      run: |
          cd Damas_Chinas
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
          horusec start -D -p="./" -o"=json" -O=horusec-config.json

    - name: Instalar dependencias
      run: |
            pip install pandas==1.3.3
            pip install pydantic==1.8.2
            pip install plotly==5.3.1
    - name: Check
      run:  |
          python -m pip --version
          python --version
    - name: Run security Tools
      run: |
          python dash.py Damas_Chinas/horusec-config.json horusec

    - name: Upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: horusec
        path: Damas_Chinas/horusec-config.json

#python -m pip install pandas pandas-profiling

    - name: Subir html        
      uses: actions/upload-artifact@v2
      with:
        name: informeinteractivo
        path: informe_interactivo.html
    - name: List files in the directory
      run: ls -R


  
  secrets-2:
    permissions:
      contents: read
      id-token: write
    name: secrrr
    runs-on: ubuntu-latest
    steps:
      - name: import secr
        id : imps
        uses: hashicorp/vault-action@v2
        with:
          url: https://sample-cluster-public-vault-0266fbaf.0bff476f.z1.hashicorp.cloud:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
                   admin/secret/data/development SEMPGREP_APP_TOKEN | TOK_SEMGREP
      - name : sequity
        uses: actions/checkout@v3
        env: 
          SEMGREP_APP_TOKEN: ${{env.TOK_SEMGREP}}
      - run: sempgrepc ci




    
