on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 9 10 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci



  check-horusec:
    name: horuscc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: CheckSecrets
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Horusec
      run: |
          cd Damas_Chinas
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
          horusec start -D -p="./" -o"=json" -O=horusec-config.json

    - name: Instalar dependencias
      run: |
            pip install pandas==1.3.3
            pip install pydantic==1.8.2
            pip install plotly==5.3.1
    - name: Check
      run:  |
          python -m pip --version
          python --version
    - name: Run security Tools
      run: |
          python dash.py Damas_Chinas/horusec-config.json horusec

    - name: Upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: horusec
        path: Damas_Chinas/horusec-config.json

#python -m pip install pandas pandas-profiling

    - name: Subir html        
      uses: actions/upload-artifact@v2
      with:
        name: informeinteractivo
        path: informe_interactivo.html
    - name: List files in the directory
      run: ls -R

  secrets:
    name: secretos
    runs-on: ubuntu-latest
    steps:
      - name: import Secretos
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url:  ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
                /v1/admin/secret/data/data as
                  

    
