# Name of this GitHub Actions workflow.
name: Semgrep

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]
  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '20 17 * * *' # Sets Semgrep to scan every day at 17:20 UTC.
    # It is recommended to change the schedule to a random time.

jobs:
  import-cifr:
    environment: Development
    name: Secrets
    runs-on: ubuntu-latest
    outputs:
      id: imp_sec
    steps:
      - name: importar_secretos
        id: imp_sec
        uses: hashicorp/vault-action@v2
        with:
          url: https://sample-cluster-public-vault-0266fbaf.0bff476f.z1.hashicorp.cloud:8200/
          token: ${{secrets.VAULT_TOKEN}}
          tlsSkipVerify: true 
          secrets: |
                   admin/secret/data/development TOKEN_GITHUB | TOKEN_GIT;
                   admin/secret/data/development SONAR_TOKEN | SONAR_TOK;
                   admin/secret/data/development SONAR_HOST_URL | SONAR_HOST;
                   admin/secret/data/development SEMGREP_APP_TOKEN | SEMGREP_APP_TOK;
      - name: Setear variables de salida
        run: echo "SECRET_TOKEN_GIT=${{ env.TOKEN_GIT }}" >> $GITHUB_ENV
          echo "SECRET_SONAR_TOK=${{ env.SONAR_TOK }}" >> $GITHUB_ENV
          echo "SECRET_SONAR_HOST=${{ env.SONAR_HOST }}" >> $GITHUB_ENV
          echo "SECRET_SEMGREP_APP_TOK=${{ env.SEMGREP_APP_TOK }}" >> $GITHUB_ENV

  otro-job:
      runs-on: ubuntu-latest
      needs: import-cifr
      steps:
        - name: Obtener secretos del job anterior
          run: |
            echo "TOKEN_GIT: ${{ needs.import-cifr.outputs.SECRET_TOKEN_GIT }}"
            echo "SONAR_TOK: ${{ needs.import-cifr.outputs.SECRET_SONAR_TOK }}"
            echo "SONAR_HOST: ${{ needs.import-cifr.outputs.SECRET_SONAR_HOST }}"
            echo "SEMGREP_APP_TOK: ${{ needs.import-cifr.outputs.SECRET_SEMGREP_APP_TOK }}"