# Name of this GitHub Actions workflow.
name: Semgrep

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]
  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '20 17 * * *' # Sets Semgrep to scan every day at 17:20 UTC.
    # It is recommended to change the schedule to a random time.

jobs:
  import-cifr:
    environment: Development
    name: Secrets
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    outputs:
      id: imp_sec
      TOKEN_GIT: ${{ steps.imp_sec.outputs.TOKEN_GIT }}
      SONAR_TOK: ${{ steps.imp_sec.outputs.SONAR_TOK }}
      SONAR_HOST: ${{ steps.imp_sec.outputs.SONAR_HOST }}
      SEMGREP_APP_TOK: ${{ steps.imp_sec.outputs.SEMGREP_APP_TOK }}
    steps:
      - name: importar_secretos
        id: imp_sec
        uses: hashicorp/vault-action@v2
        with:
          url: https://sample-cluster-public-vault-0266fbaf.0bff476f.z1.hashicorp.cloud:8200/
          token: ${{secrets.VAULT_TOKEN}}
          tlsSkipVerify: true 
          secrets: |
            admin/secret/data/development TOKEN_GITHUB | ${{ secrets.TOKEN_GIT }};
            admin/secret/data/development SONAR_TOKEN | ${{ secrets.SONAR_TOK }};
            admin/secret/data/development SONAR_HOST_URL | ${{ secrets.SONAR_HOST }};
            admin/secret/data/development SEMGREP_APP_TOKEN | ${{ secrets.SEMGREP_APP_TOK }};
  
  otro-job:
    runs-on: ubuntu-latest
    needs: import-cifr
    steps:
      - name: Obtener secretos del job anterior
        run: |
          echo "TOKEN_GIT: ${{ secrets.TOKEN_GIT }}"
          echo "SONAR_TOK: ${{ secrets.SONAR_TOK }}"
          echo "SONAR_HOST: ${{ secrets.SONAR_HOST }}"
          echo "SEMGREP_APP_TOK: ${{ secrets.SEMGREP_APP_TOK }}"
  